# Use this command to run in windows mode
# docker-compose -f docker-compose.windows.yml up

version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management

  ConsumerMicroservice:
    image: ${REGISTRY:-adearriba}/consumer:${PLATFORM:-windows}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/ConsumerMicroservice/Dockerfile
    depends_on:
      - rabbitmq

  ProducerMicroservice:
    image: ${REGISTRY:-adearriba}/producer:${PLATFORM:-windows}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/ProducerMicroservice/Dockerfile
    depends_on:
      - rabbitmq

networks:
  default:
    external:
      name: nat