# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"

  consumermicroservice:
    image: ${REGISTRY:-adearriba}/consumermicroservice:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/ConsumerMicroservice/Dockerfile
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

  producermicroservice:
    image: ${REGISTRY:-adearriba}/producermicroservice:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/ProducerMicroservice/Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
